name: V2Ray Ping Checker

on:
  schedule:
    - cron: '0 */2 * * *' # اجرای خودکار هر ۲ ساعت یکبار
  workflow_dispatch: # امکان اجرای دستی از داخل پنل گیت‌هاب

jobs:
  ping-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Ping Script
        run: python checker.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add configs.json
          git commit -m "Auto update ping results" || exit 0
          git push
